// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import Services from "@/src/pages/Services";

export default function Page() {
  return <Services />;
}
