// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import Infrastructure from "@/screens/Infrastructure";

export default function Page() {
  return <Infrastructure />;
}
