// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import Blog from "@/screens/Blog";

export default function Page() {
  return <Blog />;
}
