// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import About from "@/screens/About";

export default function Page() {
  return <About />;
}
