// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import Home from "@/src/pages/Home";

export default function Page() {
  return <Home />;
}
