#!/usr/bin/env node
/**
 * migrate-to-next.mjs
 *
 * Scaffolds a Next.js (App Router) style `app/` folder that mirrors the
 * current Vite + react-router-dom routing tree.
 *
 * It does NOT delete or move existing source files. Each generated
 * `page.tsx` simply re-exports the matching component from `src/pages/*`,
 * so after running this script you can:
 *   1. install next
 *   2. add a minimal next.config.js + tsconfig path
 *   3. start migrating piece by piece
 *
 * Run with: npm run migrate
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const APP_DIR = resolve(ROOT, "app");

// Mirror of src/App.tsx <Routes>
// path -> { component file under src/pages (no extension), dynamic? }
const ROUTES = [
  { route: "/",               page: "Home" },
  { route: "/services",       page: "Services" },
  { route: "/marketplaces",   page: "Marketplaces" },
  { route: "/marketplaces/:slug", page: "integrations/IntegrationDetail" },
  { route: "/infrastructure", page: "Infrastructure" },
  { route: "/pricing",        page: "Pricing" },
  { route: "/about",          page: "About" },
  { route: "/blog",           page: "Blog" },
  { route: "/blog/:slug",     page: "BlogPost" },
  { route: "/contact",        page: "Contact" },
];

const NOT_FOUND_PAGE = "NotFound";

function write(file, contents) {
  mkdirSync(dirname(file), { recursive: true });
  if (existsSync(file)) {
    console.log(`  skip (exists) ${file.replace(ROOT + "/", "")}`);
    return;
  }
  writeFileSync(file, contents);
  console.log(`  + ${file.replace(ROOT + "/", "")}`);
}

// Convert "/blog/:slug" -> "app/blog/[slug]"
function routeToFsPath(route) {
  if (route === "/") return APP_DIR;
  const segments = route
    .split("/")
    .filter(Boolean)
    .map((seg) => (seg.startsWith(":") ? `[${seg.slice(1)}]` : seg));
  return resolve(APP_DIR, ...segments);
}

function pageContent(pagePath, isDynamic) {
  const componentName = pagePath.split("/").pop();
  const propsType = isDynamic
    ? `\n\ntype PageProps = { params: { slug: string } };`
    : "";
  const propsArg = isDynamic ? "(props: PageProps)" : "()";
  const passProps = isDynamic ? " {...props}" : "";
  return `// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import ${componentName} from "@/screens/${pagePath}";${propsType}

export default function Page${propsArg} {
  return <${componentName}${passProps} />;
}
`;
}

function rootLayoutContent() {
  return `// AUTO-GENERATED root layout (Next.js App Router style)
import type { ReactNode } from "react";
import "@/index.css";

export const metadata = {
  title: "Ctasis",
  description: "Multichannel seller tooling",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function notFoundContent() {
  return `// AUTO-GENERATED not-found page
"use client";

import NotFound from "@/screens/${NOT_FOUND_PAGE}";

export default function NotFoundPage() {
  return <NotFound />;
}
`;
}

function readmeContent() {
  return `# app/

This folder is generated by \`npm run migrate\`.
It mirrors the current React Router tree in a Next.js App Router layout.

Routes:
${ROUTES.map((r) => `- \`${r.route}\` -> src/pages/${r.page}.tsx`).join("\n")}

Next steps to actually run as Next.js:
1. \`npm i next\`
2. Add \`next.config.js\` and update \`tsconfig.json\` (\`"jsx": "preserve"\`, include \`app\`).
3. Replace \`<BrowserRouter>\` usage with Next \`<Link>\` / \`useRouter\`.
4. Move data fetching from client to server components where possible.
`;
}

console.log(`Scaffolding Next.js style app/ at: ${APP_DIR}`);
mkdirSync(APP_DIR, { recursive: true });

write(resolve(APP_DIR, "layout.tsx"), rootLayoutContent());
write(resolve(APP_DIR, "not-found.tsx"), notFoundContent());
write(resolve(APP_DIR, "README.md"), readmeContent());

for (const { route, page } of ROUTES) {
  const dir = routeToFsPath(route);
  const isDynamic = route.includes(":");
  write(resolve(dir, "page.tsx"), pageContent(page, isDynamic));
}

console.log("\nDone. Review the generated app/ folder.");
