// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import Marketplaces from "@/src/pages/Marketplaces";

export default function Page() {
  return <Marketplaces />;
}
