// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import IntegrationDetail from "@/screens/integrations/IntegrationDetail";

type PageProps = { params: { slug: string } };

export default function Page(props: PageProps) {
  return <IntegrationDetail />;
}
