// AUTO-GENERATED by scripts/migrate-to-next.mjs
// Edit freely once you start migrating this route to Next.js.
"use client";

import Pricing from "@/screens/Pricing";

export default function Page() {
  return <Pricing />;
}
